version: '2.0'
services:
  
  mysql:
    container_name: user_mysql
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
        - MYSQL_ROOT_PASSWORD=root # TODO: Change this
        - MYSQL_USER=test
        - MYSQL_PASS=pass
        - MYSQL_DATABASE=user_db
    volumes:
      - user_mysqldb:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
      
  user-manager:
    image: user-manager/user-manager-server
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql
      
  phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - "6060:80"
volumes:
  user_mysqldb:
