version: '2.0'
services:

  user_api_db:
    container_name: user_api_db
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root # TODO: Change this
      - MYSQL_USER=test
      - MYSQL_PASS=pass
      - MYSQL_DATABASE=user_db
    volumes:
      - user_vol_db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'

  user_api:
    image: user_api
    ports:
      - "8080:8080"
    depends_on:
      - user_api_db
    links:
      - user_api_db

  chillout_api_db:
    container_name: chillout_api_db
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root # TODO: Change this
      - MYSQL_USER=test
      - MYSQL_PASS=pass
      - MYSQL_DATABASE=chillout_db
    volumes:
      - chillout_vol_db:/var/lib/mysql
    ports:
      - "3305:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
  chillout_api:
    image: chillout_api
    ports:
      - "8081:8081"
    depends_on:
      - chillout_api_db
    links:
      - chillout_api_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - chillout_api_db
      - user_api_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_HOSTS=chillout_api_db,user_api_db
    ports:
      - "6060:80"
volumes:
  user_vol_db:
  chillout_vol_db:
