version: '2'

user_management:

chill:


user_db:
    build: ../../docker-images/mysql/User
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    port: 1234:1234
 
chill_db:
    build: ../../docker-images/mysql/Chill
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    port: 1245:1245

