version: '2.0'
services:
  
  mysql:
    container_name: user_mysql
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
        - MYSQL_ROOT_PASSWORD=root # TODO: Change this
        - MYSQL_USER=test
        - MYSQL_PASS=pass
        - MYSQL_DATABASE=user_db
    volumes:
      - user_mysqldb:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
      
  user-manager:
    image: user-manager/user-manager-server
    container_name: "userAPI"
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    links:
      - mysql
    labels:
    # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain the service will respond to
      - "traefik.http.routers.user-manager.rule=Host(`user-manager.localhost`)"
      
  phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - "6060:80"
  traefik:
    image: traefik:v2.0
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
volumes:
  user_mysqldb:
