swagger: '2.0'
info:
  version: 1.0.0
  title: Chillout API
  description: An API to manage the entities in the chillout
host: localhost:8081
basePath: /api
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /products:
    post:
      description: create a product
      operationId: createProduct
      consumes:
        - application/json
      parameters:
        - name: product
          in: body
          required: true
          schema:
            $ref: '#/definitions/ProductInput'
      responses:
        '201':
          description: created
          schema:
            type: object
        400:
          description: Payload malformatted
          schema:
            type: object
    get:
      description: get the list of all products
      operationId: getProducts
      produces:
        - application/json
      parameters:
        - in: query
          type: integer
          required: false
          default: 1
          minimum: 1
          name: page
          description: Number of the page
        - in: query
          type: integer
          required: false
          default: 20
          minimum: 1
          name: pageSize
          description: Size of the page
      responses:
        200:
          description: List of users
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductOutput'
        401:
          description: Unauthorized
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object

  /products/{id}:
    patch:
      security:
      - Bearer: []
      tags:
        - "product"
      summary: "Updates the ressource"
      operationId: "updateProduct"
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          type: integer
          format: int64
          required: true
          name: id
          description: The email of the Product
        - in: body
          name: fields
          description: The fields to update
          schema:
            type: object
            properties:
              name:
                type: string
              unitPrice:
                type: string
              description:
                type: string
      responses:
        200:
          description: Description of Product
          schema:
            $ref: '#/definitions/ProductOutput'
        401:
          description: Unauthorized
          schema:
            type: object
        400:
          description: Payload malformatted
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object
    delete:
      security:
      - Bearer: []
      tags:
        - "product"
      summary: "Deletes the ressource"
      operationId: "deleteProductById"
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          type: integer
          format: int64
          required: true
          name: id
          description: The id of the Product
      responses:
        200:
          description: Deleted ressource
          schema:
            type: object
        400:
          description: Payload malformatted
          schema:
            type: object
        401:
          description: Unauthorized
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object
    get:
      security:
      - Bearer: []
      tags:
        - "product"
      summary: "Get the ressource"
      operationId: "getProductById"
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: path
          type: integer
          format: int64
          required: true
          name: id
          description: The id of the Product
      responses:
        200:
          description: Description of Product
          schema:
            $ref: '#/definitions/ProductOutput'
        401:
          description: Unauthorized
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object
  /clients:
    post:
      security:
      - Bearer: []
      tags:
        - "clients"
      summary: "Create a client"
      operationId: createClient
      consumes:
        - application/json
      parameters:
        - name: client
          in: body
          required: true
          schema:
            $ref: '#/definitions/Client'
      responses:
        201:
          description: Created
          schema:
            type: object
        400:
          description: Payload malformatted
          schema:
            type: object
        401:
          description: Unauthorized
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        409:
          description: Duplicate ressource
          schema:
            type: object
    get:
      security:
      - Bearer: []
      tags:
        - "clients"
      summary: "Get the list of all clients"
      operationId: "getClients"
      produces:
        - application/json
      parameters:
        - in: query
          type: integer
          required: false
          default: 1
          minimum: 1
          name: page
          description: Number of the page

        - in: query
          type: integer
          required: false
          default: 20
          minimum: 1
          name: pageSize
          description: Size of the page
      responses:
        200:
          description: List of Clients
          schema:
            type: array
            items:
              $ref: '#/definitions/Client'
        401:
          description: Unauthorized
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object

  /clients/{email}:
    get:
      security:
      - Bearer: []
      tags:
        - "clients"
      summary: "Gets a client by his email"
      operationId: "getClientById"
      produces:
        - application/json
      parameters:
        - in: path
          type: string
          required: true
          name: email
          description: The email of the clienz
      responses:
        200:
          description: Description of client
          schema:
            $ref: '#/definitions/Client'
        401:
          description: Unauthorized
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object

    delete:
      security:
      - Bearer: []
      tags:
        - "clients"
      summary: "Deletes a given ressource"
      operationId: "deleteClient"
      parameters:
        - name: email
          in: path
          required: true
          type: string
          description: The email of the client
      responses:
        200:
          description: deleted
          schema:
            type: object
        401:
          description: Unauthorized
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object

  /orders:
    post:
      description: create an order
      operationId: createOrder
      consumes:
        - application/json
      parameters:
      - in: body
        name: fields
        description: The fields of an order
        schema:
          type: object
          properties:
            email:
              type: string
            order:
              type: array
              items:
                $ref: '#/definitions/OrderItem'
      responses:
        '201':
          description: created
          schema:
            type: object
        400:
          description: Payload malformatted
          schema:
            type: object
        401:
          description: Unauthorized
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        409:
          description: Duplicate ressource
          schema:
            type: object

    get:
      security:
      - Bearer: []
      description: get the list of all orders
      operationId: getOrders
      produces:
        - application/json
      parameters:
        - in: query
          type: integer
          required: false
          default: 1
          minimum: 1
          name: page
          description: Number of the page
        - in: query
          type: integer
          required: false
          default: 20
          minimum: 1
          name: pageSize
          description: Size of the page
      responses:
        200:
          description: List of users
          schema:
            type: array
            items:
              $ref: '#/definitions/Order'
        401:
          description: Unauthorized
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object

  /orders/{id}:
    get:
      security:
      - Bearer: []
      tags:
          - "orders"
      summary: "Gets a order by his id"
      operationId: "getOrderById"
      produces:
        - application/json
      parameters:
        - in: path
          type: string
          required: true
          name: id
          description: The id of the order
      responses:
        200:
          description: Description of order
          schema:
            $ref: '#/definitions/Order'
        401:
          description: Unauthorized
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object
    delete:
      security:
      - Bearer: []
      tags:
        - "orders"
      summary: "Deletes a given ressource"
      operationId: "deleteOrder"
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: The id of the order
      responses:
        200:
          description: deleted
          schema:
            type: object
        401:
          description: Unauthorized
          schema:
            type: object
        403:
          description: Forbidden
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object

definitions:
  Client:
    type: object
    properties:
      email:
        type: string
  Product:
    type: object
    properties:
      name:
        type: string
      unitPrice:
        type: number
        format: double
      description:
        type: string
  ProductInput:
    allOf:
      - $ref: '#/definitions/Product'
      - type: object
  ProductOutput:
    allOf:
      - $ref: '#/definitions/Product'
      - type: object
      - properties:
          id:
            type: integer
            format: int64
  OrderItem:
    type: object
    properties:
      id:
        type: integer
        format: int64
      product:
        $ref: '#/definitions/ProductOutput'
      quantity:
        type: integer
  Order:
    type: object
    properties:
      id:
        type: integer
        format: int64
      client:
        $ref: '#/definitions/Client'
      orderItems:
        type: array
        items:
          $ref: '#/definitions/OrderItem'